# ---- Formula parsing (no ergm needed) ----------------------------------------

# One formula exercising every term shape ergm accepts: redundant
# parentheses, ::/:::-qualified names, offset() (also around a qualified
# name), curved terms, multi-attribute and repeated terms, bipartite terms,
# and an exotic call head, which is named rather than rejected
result <- parse_ergm_formula(
  y ~ ((edges + ergm::nodematch("gender")) + offset(nodefactor("race"))) +
    offset(ergm::edges) + gwesp(0.5, fixed = TRUE) +
    nodemix("race", "gender") + nodecov("wealth") +
    ergm:::nodecov("priorates") + b1star(2) + b1factor("type") +
    b2nodematch("group") + obj$fn(1)
)
expect_inherits(result, "data.frame")
expect_equal(result$term, c(
  "edges", "nodematch", "offset(nodefactor)", "offset(edges)", "gwesp",
  "nodemix", "nodecov", "nodecov", "b1star", "b1factor", "b2nodematch",
  "obj$fn"
))
expect_equal(result$attribute, c(
  NA, "gender", "race", NA, NA, "race, gender", "wealth", "priorates", NA,
  "type", "group", NA
))
# No fitted model, so no coefficient statistics
expect_true(all(is.na(result[, c("estimate", "se", "pvalue")])))
expect_true(all(c("description", "math", "figure") %in% names(result)))

# One-sided formulas parse the same way
expect_equal(parse_ergm_formula(~ edges + triangle)$term,
  c("edges", "triangle"))

# parse_ergm_formula errors on non-formula input
expect_error(parse_ergm_formula("not a formula"))
expect_error(parse_ergm_formula(42))

# parse_ergm_formula validates the 'directed' argument
expect_error(parse_ergm_formula(y ~ edges, directed = NA))
expect_error(parse_ergm_formula(y ~ edges, directed = c(TRUE, FALSE)))
expect_error(parse_ergm_formula(y ~ edges, directed = "yes"))

# A left-hand side that is not a network (undefined, or some other object)
# leaves directedness undecided, so the undirected default applies
expect_true(grepl("i<j", parse_ergm_formula(undefined_object ~ edges)$math))
expect_true(grepl("i<j", parse_ergm_formula(letters ~ edges)$math))

# parse_ergm_model errors on non-ergm input
expect_error(parse_ergm_model(list()))
expect_error(parse_ergm_model(lm(1 ~ 1)))

# ---- Model parsing (uses pre-fitted ergm objects) ----------------------------

if (requireNamespace("network", quietly = TRUE) &&
    requireNamespace("ergm", quietly = TRUE)) {

  library(network)
  library(ergm)

  # Load pre-fitted models (generated by data-raw/fit_ergm_models.R)
  fit      <- readRDS(system.file("fits", "fit_edges.rds", package = "tabulergm"))
  fit2     <- readRDS(system.file("fits", "fit_nodematch.rds", package = "tabulergm"))
  fit3     <- readRDS(system.file("fits", "fit_nodematch_diff.rds", package = "tabulergm"))
  fit4     <- readRDS(system.file("fits", "fit_nodemix.rds", package = "tabulergm"))
  fit_bip  <- readRDS(system.file("fits", "fit_bipartite.rds", package = "tabulergm"))
  fit_bip_dsp <- readRDS(system.file("fits", "fit_bipartite_dsp.rds", package = "tabulergm"))
  fit_bip_factor <- readRDS(system.file("fits", "fit_bipartite_factor.rds", package = "tabulergm"))
  fit_bip_match <- readRDS(system.file("fits", "fit_bipartite_match.rds", package = "tabulergm"))
  fit_nc_twice <- readRDS(system.file("fits", "fit_nodecov_twice.rds", package = "tabulergm"))

  # parse_ergm_model works with a simple edges-only model
  result <- parse_ergm_model(fit)
  expect_inherits(result, "data.frame")
  expect_true(all(c("term", "coef_name", "attribute", "estimate",
                     "se", "pvalue", "description", "math", "figure")
                   %in% names(result)))
  expect_equal(result$term, "edges")
  expect_equal(result$coef_name, "edges")
  expect_true(is.numeric(result$estimate))
  expect_true(is.numeric(result$se))
  expect_true(is.numeric(result$pvalue))
  # edges is a well-known term; expect a non-NA description
  expect_false(is.na(result$description[result$term == "edges"]))

  # parse_ergm_model maps expanded nodematch terms
  result2 <- parse_ergm_model(fit2)
  expect_true(nrow(result2) >= 2L)
  expect_true("edges" %in% result2$term)
  expect_true("nodematch" %in% result2$term)
  nm_row <- result2[result2$term == "nodematch", ]
  expect_equal(nm_row$attribute[1], "group")

  # Coefficient statistics are computed directly from coef()/vcov() rather
  # than summary(), so ergm's per-minor-release compatibility warning does
  # not fire for fits made with an older ergm (#35). Parity against
  # summary() guards the computation against future ergm changes.
  summary_coefs <- suppressWarnings(summary(fit2))[["coefficients"]]
  expect_equal(unname(result2$estimate), unname(summary_coefs[, "Estimate"]))
  expect_equal(unname(result2$se), unname(summary_coefs[, "Std. Error"]))
  expect_equal(unname(result2$pvalue), unname(summary_coefs[, "Pr(>|z|)"]))
  expect_equal(result2$coef_name, rownames(summary_coefs))

  # Parsing a shipped fit is quiet. On CI, where ergm is newer than the one
  # that produced inst/fits/, this is what catches the warning.
  expect_silent(parse_ergm_model(fit))

  # The same for a fit from a much older ergm, so the check also bites on a
  # machine whose ergm predates the warning.
  stale_fit <- fit
  stale_fit[["ergm_version"]] <- as.package_version("3.9.4")
  expect_silent(parse_ergm_model(stale_fit))
  expect_equal(parse_ergm_model(stale_fit)$estimate, result$estimate)

  # parse_ergm_model works with nodematch diff=TRUE (multiple coefficients)
  result3 <- parse_ergm_model(fit3)
  # With diff=TRUE, nodematch expands to one coef per level
  nm_rows <- result3[result3$term == "nodematch", ]
  expect_true(nrow(nm_rows) >= 2L)
  expect_true(all(nm_rows$attribute == "color"))

  # parse_ergm_model handles mixing terms (nodemix)
  result4 <- parse_ergm_model(fit4)
  expect_true("nodemix" %in% result4$term)
  mix_rows <- result4[result4$term == "nodemix", ]
  # nodemix produces multiple coefficients for mixing categories
  expect_true(nrow(mix_rows) >= 1L)
  expect_true(all(mix_rows$attribute == "role"))

  # parse_ergm_model maps repeated terms to occurrence-specific attributes
  # (regression: attributes used to be joined by term name, so duplicate
  # terms all reported the first occurrence's attribute)
  result_nc <- parse_ergm_model(fit_nc_twice)
  expect_equal(result_nc$term, c("edges", "nodecov", "nodecov"))
  expect_equal(
    result_nc$coef_name,
    c("edges", "nodecov.wealth", "nodecov.priorates")
  )
  expect_equal(
    result_nc$attribute,
    c(NA_character_, "wealth", "priorates")
  )

  # parse_ergm_model handles bipartite network with b1star
  result_bip <- parse_ergm_model(fit_bip)
  expect_true("edges" %in% result_bip$term)
  expect_true("b1star" %in% result_bip$term)

  # When ergm cannot rebuild the model (e.g. a saved fit whose formula
  # environment is gone), coefficients still map to their terms by name,
  # both with a dot separator (nodematch.color.blue) and without (b1star2)
  unbuildable <- function(fit) {
    environment(fit$formula) <- emptyenv()
    parse_ergm_model(fit)
  }
  expect_equal(unbuildable(fit3)$term, result3$term)
  expect_equal(unbuildable(fit_bip)$term, result_bip$term)

  # parse_ergm_model handles bipartite gwb*dsp terms
  result_bip_dsp <- parse_ergm_model(fit_bip_dsp)
  expect_true("gwb1dsp" %in% result_bip_dsp$term)
  expect_true("gwb2dsp" %in% result_bip_dsp$term)
  expect_false(is.na(result_bip_dsp$math[result_bip_dsp$term == "gwb1dsp"][1]))
  expect_false(is.na(result_bip_dsp$math[result_bip_dsp$term == "gwb2dsp"][1]))

  # parse_ergm_model handles bipartite factor terms
  result_bip_factor <- parse_ergm_model(fit_bip_factor)
  expect_true("b1factor" %in% result_bip_factor$term)
  expect_true("b2factor" %in% result_bip_factor$term)
  expect_true(all(result_bip_factor$attribute[result_bip_factor$term == "b1factor"] == "a"))
  expect_true(all(result_bip_factor$attribute[result_bip_factor$term == "b2factor"] == "b"))
  expect_false(is.na(result_bip_factor$math[result_bip_factor$term == "b1factor"][1]))
  expect_false(is.na(result_bip_factor$math[result_bip_factor$term == "b2factor"][1]))

  # parse_ergm_model handles bipartite nodematch terms
  result_bip_match <- parse_ergm_model(fit_bip_match)
  expect_true("b1nodematch" %in% result_bip_match$term)
  expect_true("b2nodematch" %in% result_bip_match$term)
  expect_true(all(result_bip_match$attribute[result_bip_match$term == "b1nodematch"] == "a"))
  expect_true(all(result_bip_match$attribute[result_bip_match$term == "b2nodematch"] == "b"))
  expect_false(is.na(result_bip_match$math[result_bip_match$term == "b1nodematch"][1]))
  expect_false(is.na(result_bip_match$math[result_bip_match$term == "b2nodematch"][1]))
}
