# ---- tabulergm_table.formula (no ergm needed) --------------------------------

# tabulergm_table dispatches on formula
f <- y ~ edges + triangle
result <- tabulergm_table(f)
expect_inherits(result, "data.frame")
expect_equal(names(result), c("term", "figure", "math", "description"))
expect_equal(result$term, c("edges", "triangle"))

# formula table excludes coefficient statistics
expect_false("estimate" %in% names(result))
expect_false("se" %in% names(result))
expect_false("pvalue" %in% names(result))

# formula table with attributes
f2 <- y ~ edges + nodematch("gender")
result2 <- tabulergm_table(f2)
expect_equal(result2$term, c("edges", "nodematch"))
# attribute column is NOT in the formula-only output
expect_false("attribute" %in% names(result2))

# tabulergm_table.formula handles one-sided formulas
f3 <- ~ edges + triangle
result3 <- tabulergm_table(f3)
expect_equal(result3$term, c("edges", "triangle"))

# ---- tabulergm_table.ergm (uses pre-fitted ergm object) ----------------------

if (requireNamespace("network", quietly = TRUE) &&
    requireNamespace("ergm", quietly = TRUE)) {

  library(network)
  library(ergm)

  # Load pre-fitted model (generated by data-raw/fit_ergm_models.R)
  fit <- readRDS(system.file("fits", "fit_edges.rds", package = "tabulergm"))

  # Basic ergm table has default columns
  result <- tabulergm_table(fit)
  expect_inherits(result, "data.frame")
  expect_equal(names(result), c("term", "figure", "estimate", "se", "pvalue"))
  expect_equal(result$term, "edges")
  expect_true(is.numeric(result$estimate))
  expect_true(is.numeric(result$se))
  expect_true(is.numeric(result$pvalue))

  # Optional columns included when requested
  result_desc <- tabulergm_table(fit, include_description = TRUE)
  expect_true("description" %in% names(result_desc))

  result_math <- tabulergm_table(fit, include_math = TRUE)
  expect_true("math" %in% names(result_math))

  result_attr <- tabulergm_table(fit, include_attribute = TRUE)
  expect_true("attribute" %in% names(result_attr))

  # All optional columns together
  result_all <- tabulergm_table(
    fit,
    include_description = TRUE,
    include_math = TRUE,
    include_attribute = TRUE
  )
  expect_true(all(c("term", "figure", "estimate", "se", "pvalue",
                    "description", "math", "attribute") %in%
                    names(result_all)))

  # coef_name column is NOT included in tabulergm_table output
  expect_false("coef_name" %in% names(result_all))

  # Markdown format (requires knitr)
  if (requireNamespace("knitr", quietly = TRUE)) {
    md <- tabulergm_table(fit, format = "markdown")
    expect_inherits(md, "knitr_kable")

    html <- tabulergm_table(fit, format = "html")
    expect_inherits(html, "knitr_kable")

    # ---- math column is wrapped in $$ for markdown -------------------------

    md_math <- tabulergm_table(fit, include_math = TRUE, format = "markdown")
    md_str <- paste(as.character(md_math), collapse = "\n")
    # The math expression should be wrapped in $$...$$ delimiters
    expect_true(grepl("\\$\\$", md_str),
      info = "markdown math column contains $$ delimiters")

    # ---- math column is wrapped in $$ for html ----------------------------

    html_math <- tabulergm_table(fit, include_math = TRUE, format = "html")
    html_str <- paste(as.character(html_math), collapse = "\n")
    expect_true(grepl("\\$\\$", html_str),
      info = "html math column contains $$ delimiters")

    # ---- figure column uses <img> tags for markdown ------------------------

    md_fig <- tabulergm_table(fit, format = "markdown")
    md_fig_str <- paste(as.character(md_fig), collapse = "\n")
    # The figure cell should contain an <img> tag (or be empty when no figure)
    has_figure <- !is.na(tabulergm_table(fit)[["figure"]])
    if (any(has_figure)) {
      expect_true(grepl("<img", md_fig_str),
        info = "markdown figure column uses <img> tags")
    }

    # ---- figure column uses <img> tags for html ---------------------------

    html_fig_str <- paste(as.character(html), collapse = "\n")
    if (any(has_figure)) {
      expect_true(grepl("<img", html_fig_str),
        info = "html figure column uses <img> tags")
    }

    # ---- tabulergm_view dispatches without error --------------------------

    # Only test that the function returns a path; skip browser opening
    tmp <- tabulergm_view(fit)
    expect_true(file.exists(tmp),
      info = "tabulergm_view creates a temporary HTML file")
    expect_true(grepl("\\.html$", tmp),
      info = "tabulergm_view returns a .html file path")

    # The HTML file contains MathJax script tag
    html_content <- paste(readLines(tmp), collapse = "\n")
    expect_true(grepl("mathjax", tolower(html_content)),
      info = "tabulergm_view HTML includes MathJax")

    # tabulergm_view also works on a formula
    tmp_f <- tabulergm_view(network ~ edges)
    expect_true(file.exists(tmp_f),
      info = "tabulergm_view.formula creates a temporary HTML file")
  }
}
