# ---- tabulergm_table.formula (no ergm needed) --------------------------------

# tabulergm_table dispatches on formula
f <- y ~ edges + triangle
result <- tabulergm_table(f)
expect_inherits(result, "data.frame")
expect_equal(names(result), c("term", "figure", "math", "description"))
expect_equal(result$term, c("edges", "triangle"))

# formula table excludes coefficient statistics
expect_false("estimate" %in% names(result))
expect_false("se" %in% names(result))
expect_false("pvalue" %in% names(result))

# formula table with attributes
f2 <- y ~ edges + nodematch("gender")
result2 <- tabulergm_table(f2)
expect_equal(result2$term, c("edges", "nodematch"))
# attribute column is NOT in the formula-only output
expect_false("attribute" %in% names(result2))

# tabulergm_table.formula handles one-sided formulas
f3 <- ~ edges + triangle
result3 <- tabulergm_table(f3)
expect_equal(result3$term, c("edges", "triangle"))

# Markdown keeps TeX inequality symbols raw so downstream renderers can parse
# the math expression.
if (requireNamespace("knitr", quietly = TRUE)) {
  md_formula <- tabulergm_table(y ~ edges, format = "markdown")
  md_formula_str <- paste(as.character(md_formula), collapse = "\n")
  expect_true(grepl("\\sum_{i<j} y_{ij}", md_formula_str, fixed = TRUE),
    info = "markdown math keeps raw '<' in TeX")
  expect_false(grepl("\\sum_{i&lt;j} y_{ij}", md_formula_str, fixed = TRUE),
    info = "markdown math does not HTML-escape '<' in TeX")
}

# ---- tabulergm_table.ergm (uses pre-fitted ergm object) ----------------------

if (requireNamespace("network", quietly = TRUE) &&
    requireNamespace("ergm", quietly = TRUE)) {

  library(network)
  library(ergm)

  # Load pre-fitted model (generated by data-raw/fit_ergm_models.R)
  fit <- readRDS(system.file("fits", "fit_edges.rds", package = "tabulergm"))

  # Basic ergm table has default columns
  result <- tabulergm_table(fit)
  expect_inherits(result, "data.frame")
  expect_equal(names(result), c("term", "figure", "estimate", "se", "pvalue"))
  expect_equal(result$term, "edges")
  expect_true(is.numeric(result$estimate))
  expect_true(is.numeric(result$se))
  expect_true(is.numeric(result$pvalue))

  # Optional columns included when requested
  result_desc <- tabulergm_table(fit, include_description = TRUE)
  expect_true("description" %in% names(result_desc))

  result_math <- tabulergm_table(fit, include_math = TRUE)
  expect_true("math" %in% names(result_math))

  result_attr <- tabulergm_table(fit, include_attribute = TRUE)
  expect_true("attribute" %in% names(result_attr))

  # All optional columns together
  result_all <- tabulergm_table(
    fit,
    include_description = TRUE,
    include_math = TRUE,
    include_attribute = TRUE
  )
  expect_true(all(c("term", "figure", "estimate", "se", "pvalue",
                    "description", "math", "attribute") %in%
                    names(result_all)))

  # coef_name column is NOT included in tabulergm_table output
  expect_false("coef_name" %in% names(result_all))

  # Markdown format (requires knitr)
  if (requireNamespace("knitr", quietly = TRUE)) {
    md <- tabulergm_table(fit, format = "markdown")
    expect_inherits(md, "knitr_kable")

    html <- tabulergm_table(fit, format = "html")
    expect_inherits(html, "knitr_kable")

    # ---- math column is wrapped in $$ for markdown -------------------------

    md_math <- tabulergm_table(fit, include_math = TRUE, format = "markdown")
    md_str <- paste(as.character(md_math), collapse = "\n")
    # The math expression should be wrapped in $$...$$ delimiters
    expect_true(grepl("\\$\\$", md_str),
      info = "markdown math column contains $$ delimiters")

    # ---- math column is wrapped in $$ for html ----------------------------

    html_math <- tabulergm_table(fit, include_math = TRUE, format = "html")
    html_str <- paste(as.character(html_math), collapse = "\n")
    expect_true(grepl("\\$\\$", html_str),
      info = "html math column contains $$ delimiters")

    # Inequality symbols should be HTML-escaped so MathJax can parse reliably
    html_formula <- tabulergm_table(
      network ~ b2nodematch("group"),
      format = "html"
    )
    html_formula_str <- paste(as.character(html_formula), collapse = "\n")
    expect_true(grepl("&lt;", html_formula_str),
      info = "html math escapes '<' as &lt; in TeX")

    # ---- figure column uses <img> tags for markdown ------------------------

    md_fig <- tabulergm_table(fit, format = "markdown")
    md_fig_str <- paste(as.character(md_fig), collapse = "\n")
    # The figure cell should contain an <img> tag (or be empty when no figure)
    has_figure <- !is.na(tabulergm_table(fit)[["figure"]])
    if (any(has_figure)) {
      expect_true(grepl("<img", md_fig_str),
        info = "markdown figure column uses <img> tags")
      expect_true(grepl("style=\"width:80px;max-width:100%;\"",
        md_fig_str,
        fixed = TRUE
      ), info = "markdown figure style sets width and max-width")
      expect_false(grepl("height:80px", md_fig_str, fixed = TRUE),
        info = "markdown figure style does not set a fixed height")
    }

    # ---- figure column uses <img> tags for html ---------------------------

    html_fig_str <- paste(as.character(html), collapse = "\n")
    if (any(has_figure)) {
      expect_true(grepl("<img", html_fig_str),
        info = "html figure column uses <img> tags")
      expect_true(grepl("style=\"width:80px;max-width:100%;\"",
        html_fig_str,
        fixed = TRUE
      ), info = "html figure style sets width and max-width")
      expect_false(grepl("height:80px", html_fig_str, fixed = TRUE),
        info = "html figure style does not set a fixed height")
      expect_true(grepl("data:image/[^;]+;base64,", html_fig_str),
        info = "html figure column inlines image data as data URI")
    }

    # ---- markdown figures can be copied to a user folder ------------------

    local({
      src <- tempfile(fileext = ".png")
      writeLines("fake image content", src)
      out_dir <- tempfile("tabulergm-figures-")
      dir.create(out_dir)

      old_wd <- setwd(out_dir)
      on.exit(setwd(old_wd), add = TRUE)

      df <- data.frame(
        term = "Custom Term",
        figure = src,
        stringsAsFactors = FALSE
      )
      processed <- tabulergm:::.preprocess_columns(
        df,
        "markdown",
        figures_dir = "assets"
      )

      expect_true(file.exists(file.path(out_dir, "assets", "custom-term.png")),
        info = "manual figures_dir copies markdown figures")
      expect_true(grepl('<img src="assets/custom-term.png"',
        processed$figure,
        fixed = TRUE
      ), info = "manual figures_dir rewrites markdown figure src")
    })

    # ---- markdown figures use the active knitr figure path ----------------

    local({
      old_knit <- knitr::opts_knit$get()
      old_current <- knitr::opts_current$get()
      on.exit(knitr::opts_knit$set(old_knit), add = TRUE)
      on.exit(knitr::opts_current$set(old_current), add = TRUE)

      src <- tempfile(fileext = ".png")
      writeLines("fake image content", src)
      out_dir <- tempfile("tabulergm-knitr-figures-")
      dir.create(out_dir)

      knitr::opts_knit$set(
        output.dir = out_dir,
        rmarkdown.pandoc.to = "gfm"
      )
      knitr::opts_current$set(fig.path = "man/figures/README-")

      df <- data.frame(
        term = "Edges",
        figure = src,
        stringsAsFactors = FALSE
      )
      processed <- tabulergm:::.preprocess_columns(df, "markdown")

      expect_true(file.exists(file.path(out_dir, "man", "figures",
        "README-edges.png"
      )), info = "knitr fig.path prefix receives markdown figures")
      expect_true(grepl('<img src="man/figures/README-edges.png"',
        processed$figure,
        fixed = TRUE
      ), info = "knitr fig.path prefix rewrites markdown figure src")

      knitr::opts_current$set(fig.path = "README_files/figure-gfm/")
      src_dir <- tempfile(fileext = ".png")
      writeLines("fake image content", src_dir)
      df_dir <- data.frame(
        term = "Triangle",
        figure = src_dir,
        stringsAsFactors = FALSE
      )
      processed_dir <- tabulergm:::.preprocess_columns(df_dir, "markdown")

      expect_true(file.exists(file.path(out_dir, "README_files",
        "figure-gfm", "triangle.png"
      )), info = "knitr fig.path directory receives markdown figures")
      expect_true(grepl('<img src="README_files/figure-gfm/triangle.png"',
        processed_dir$figure,
        fixed = TRUE
      ), info = "knitr fig.path directory rewrites markdown figure src")
      expect_false(grepl("//", processed_dir$figure, fixed = TRUE),
        info = "knitr fig.path directory does not emit a double slash")
    })

    # ---- tabulergm_view dispatches without error --------------------------

    # Only test that the function returns a path; skip browser opening
    tmp <- tabulergm_view(fit)
    expect_true(file.exists(tmp),
      info = "tabulergm_view creates a temporary HTML file")
    expect_true(grepl("\\.html$", tmp),
      info = "tabulergm_view returns a .html file path")

    # The HTML file contains MathJax script tag
    html_content <- paste(readLines(tmp), collapse = "\n")
    expect_true(grepl("mathjax", tolower(html_content)),
      info = "tabulergm_view HTML includes MathJax")
    expect_true(grepl("data:image/[^;]+;base64,", html_content),
      info = "tabulergm_view HTML inlines figures as data URIs")

    # tabulergm_view also works on a formula
    tmp_f <- tabulergm_view(network ~ edges)
    expect_true(file.exists(tmp_f),
      info = "tabulergm_view.formula creates a temporary HTML file")
  }
}
